# Template for bdc build YAML file. See the bdc README.md for documentation.

bdc_min_version: "1.22"
master_parse_min_version: "1.16"

course_info:
  name: coursename
  title: "A Readable Title for this Course" # defaults to <name>
  version: 1.0.0
  #copyright_year: 2015
  deprecated: false
  type: self-paced

use_profiles: false

variables:
  foo: bar

bundle:
  zipfile: course.zip
  files:
    -
      src: 00_README.pdf
      dest: $filename
    -
      src: Labs.dbc
      dest: Lessons.dbc

#top_dbc_folder_name: ${course_name}

student_dbc: Lessons.dbc
#student_dbc: ${course_id}.dbc

notebook_type_name:
  exercises: ""
  answers: Solutions
  #instructor: instructor

#keep_lab_dirs: false

markdown:
  #html_stylesheet:

#student_dir: StudentFiles

#instructor_dir: InstructorFiles

src_base: /Users/bmc/src/databricks/training/modules

misc_files:
  -
    src: ClassSetup.pdf
    dest: $filename
  -
    src: InstructorFiles/Schedule.pdf
    dest: InstructorFiles/$filename
  -
    src: InstructorFiles/Preparation.md
    dest: InstructorFiles
    dest_is_dir: true
  -
    src: ../../README_template.html
    dest: 00_README.pdf
    template: true

notebook_defaults:
  master:
    enabled: true
    scala: false
    sql: true
    heading:
      #path: /path/to/alternate/notebook/heading
      #enabled: false
    footer:
      #path: /path/to/alternate/notebook/footer
      #enabled: false
  dest: $basename.$target_extension

  variables:
    suffix: ${notebook_type[0]} # expanded during processing

notebooks:
  -
    src: Overview-History/Introductions.py
    dest: $filename
    master:
      enabled: true
      r: false
      scala: true
      sql: true
      python: true
  -
    src: Module1/Notebook1.scala
    dest: Module1/${target_lang}/01-Intro-$notebook_type.$target_extension
    master:
      enabled: true
      r: false
      scala: true
      sql: false
      python: true
  -
    src: Module2/Includes/Shared.py
    dest: $target_lang/Module2/Includes/$basename.$target_extension
    upload_download: false
    master:
      enabled: true
      scala: false
      add_heading: false

slides:
  -
    src: Overview-History/Welcome-Overview.pptx
    dest: 01-${filename}
  -
    src: RDD-Fundamentals/RDD-Fundamentals.pptx
    dest: 02-${filename}

datasets:
  -
    src: ../../datasets/tom-sawyer/tom-sawyer.txt
    dest: tom-sawyer
  -
    src: ../../datasets/bigrams/bigrams.zip
    dest: bigrams
